### ISSUE TITLE
NoClassDefFoundError when running Robolectric 2.4/3.0 with Gradle 2.3 on Travis CI

### ISSUE THREAD

**Issue by johnjohndoe** [robolectric/robolectric#1960]
In my Android library [TypedPreferences](https://github.com/johnjohndoe/TypedPreferences) I am running tests using Robolectric 2.4. I use Gradle v.2.2.1.
Since there are newer versions available I want to update Gradle. The minimum step is to [update to Gradle 2.3](https://github.com/johnjohndoe/TypedPreferences/commit/fca90afc0164a8197fab701918a18f960c57a9d8). I can successfully run the tests on my local machine. When I run the tests on Travis CI they fail with `java.lang.NoClassDefFoundError` as you see here:

* [Travis CI log for Update Gradle wrapper to v.2.3. (Robolectric v.2.4)](https://travis-ci.org/johnjohndoe/TypedPreferences/builds/72305902)

The virtual environment is defined by this `.travis.yml`:

``` yaml
language: android

android:
  components:

    # All the build system components should be at the latest version
    - tools
    - platform-tools
    - build-tools-22.0.1
    - android-22

    # The libraries we can't get from Maven Central or similar
    - extra-android-support
    - extra-android-m2repository

script:
  - ./gradlew clean test  # run tests
```
